### ISSUE TITLE
Only generates the tree of the classes singles

### ISSUE THREAD

**Issue by mibaldi** [tentenponce/KoinGraph#6]
Factory interfaces is no showing on the tree
![image](https://user-images.githubusercontent.com/3670131/60038554-f928ef80-96b4-11e9-8e79-d618b206f83e.png)
![image](https://user-images.githubusercontent.com/3670131/60038588-11990a00-96b5-11e9-98f3-6c03eca1f552.png)

**Comment by tentenponce** [comment]
Thanks for filing this issue, I forgot that Koin has `factory` too. Will work on this and notify you here once done. 😄
