### ISSUE TITLE
Graph module with scope

### ISSUE THREAD

**Issue by mibaldi** [tentenponce/KoinGraph#8]
I use also injection with scope in activities like this:
![image](https://user-images.githubusercontent.com/3670131/60069450-273d1c80-9713-11e9-83af-7a213ce73aa4.png)
the tool support this type of annotation?

**Comment by tentenponce** [comment]
This is noted, will also support this. Thanks.

**Comment by mibaldi** [comment]
i used recent version and scope is not supported

**Comment by tentenponce** [comment]
I've tested the exact format (base on your screenshot) and add tests:

Here's the sample format that KoinGraph trying to parse:

```
single { ComponentA(get(), get()) }
      single { ComponentB() }
      factory { FactoryA(get(), get()) }
      factory { FactoryB() } 
      viewModel { ViewModelA(get(), get(), get(), get()) }
      viewModel { ViewModelB() }
      scope(named<Activity>()) {
        scoped { ScopeA() }
        scoped { ScopeB() }
      }
```

And here's the expected output:
`['ComponentA', 'ComponentB', 'FactoryA', 'FactoryB', 'ViewModelA', 'ViewModelB', 'ScopeA', 'ScopeB']`

Full test: https://github.com/tentenponce/KoinGraph/blob/master/test/domain/DependencyReaderHelperTest.js

How exactly the bug behave?

**Comment by mibaldi** [comment]
The scope that I don't see are those that have parameters in body.
![image](https://user-images.githubusercontent.com/3670131/60913698-39c56300-a288-11e9-87b4-820f01c0282a.png)

![image](https://user-images.githubusercontent.com/3670131/60913735-519ce700-a288-11e9-9818-0f6e8c6f2eb0.png)

only i see router and use case, not the presenter. 
I try with one little project with the same struct and it works
![image](https://user-images.githubusercontent.com/3670131/60913885-a3de0800-a288-11e9-9fbd-eb28dff5e9a5.png)
![image](https://user-images.githubusercontent.com/3670131/60913916-b35d5100-a288-11e9-8a01-e9646cdb4c92.png)

**Comment by mibaldi** [comment]
Hi, i try with another example and i found the error, when i use one Activity extend of on BaseActivity like this : 
`class BaseMvpActivity<V, T : BaseMvpPresenter<V>>() : AppCompatActivity()`
the tool not work correctly.
but if i change to 
`class BaseMvpActivity<V>() : AppCompatActivity()` works

**Comment by tentenponce** [comment]
I will have a look on this, this will surely help.

**Comment by tentenponce** [comment]
Hi, KoinGraph still works fine even the class has generics on it. I've created tests for it:

https://github.com/tentenponce/KoinGraph/pull/11/files#diff-13bc62182156aa4b3f2e463c77513f9e

Can you share your `ProfilePresenter` class?

**Comment by mibaldi** [comment]
https://gist.github.com/mibaldi/5b3390b5a745edc698a7d57ad6f9a61e
isn't my original profilepresenter but is the same case

**Comment by tentenponce** [comment]
Fixed on https://github.com/tentenponce/KoinGraph/pull/11. 

Problem is with the `ClassCastHelper`, it returns true even the class is parameter instead of extension or interface. Tests included on `ClassCastHelperTest`.
